# Generated by Django 5.0 on 2023-12-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField(auto_now=True)),
                ('_trade_code', models.CharField(max_length=100)),
                ('_high', models.FloatField()),
                ('_low', models.FloatField()),
                ('_open', models.FloatField()),
                ('_close', models.FloatField()),
                ('_volume', models.IntegerField()),
            ],
        ),
    ]
