# Generated by Django 5.0 on 2023-12-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_alter_stockmodel__date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_close',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_high',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_low',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_open',
            new_name='open',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_trade_code',
            new_name='trade_code',
        ),
        migrations.RenameField(
            model_name='stockmodel',
            old_name='_volume',
            new_name='volume',
        ),
    ]
