# Generated by Django 5.0 on 2023-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0003_rename__close_stockmodel_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='open',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmodel',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
